/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCanalOficialRouteImport } from './routes/_authenticated/canal-oficial'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRespostasRapidasRouteImport } from './routes/_authenticated/respostas-rapidas'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as SenhaEsqueciRouteImport } from './routes/senha.esqueci'
import { Route as SenhaRedefinirRouteImport } from './routes/senha.redefinir'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedContatosIdRouteImport } from './routes/_authenticated/contatos.$id'
import { Route as AuthenticatedIaIndexRouteImport } from './routes/_authenticated/ia.index'
import { Route as AuthenticatedIaAgentesRouteImport } from './routes/_authenticated/ia.agentes'
import { Route as AuthenticatedIaHabilidadesRouteImport } from './routes/_authenticated/ia.habilidades'
import { Route as AuthenticatedIaPropostasRouteImport } from './routes/_authenticated/ia.propostas'
import { Route as AuthenticatedNegociosIdRouteImport } from './routes/_authenticated/negocios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanalOficialRoute =
  AuthenticatedCanalOficialRouteImport.update({
    id: '/canal-oficial',
    path: '/canal-oficial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRespostasRapidasRoute =
  AuthenticatedRespostasRapidasRouteImport.update({
    id: '/respostas-rapidas',
    path: '/respostas-rapidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SenhaEsqueciRoute = SenhaEsqueciRouteImport.update({
  id: '/senha/esqueci',
  path: '/senha/esqueci',
  getParentRoute: () => rootRouteImport,
} as any)
const SenhaRedefinirRoute = SenhaRedefinirRouteImport.update({
  id: '/senha/redefinir',
  path: '/senha/redefinir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedContatosIdRoute = AuthenticatedContatosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedContatosRoute,
} as any)
const AuthenticatedIaIndexRoute = AuthenticatedIaIndexRouteImport.update({
  id: '/ia/',
  path: '/ia/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaAgentesRoute = AuthenticatedIaAgentesRouteImport.update({
  id: '/ia/agentes',
  path: '/ia/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaHabilidadesRoute =
  AuthenticatedIaHabilidadesRouteImport.update({
    id: '/ia/habilidades',
    path: '/ia/habilidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIaPropostasRoute =
  AuthenticatedIaPropostasRouteImport.update({
    id: '/ia/propostas',
    path: '/ia/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegociosIdRoute = AuthenticatedNegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/canal-oficial': typeof AuthenticatedCanalOficialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/contatos': typeof AuthenticatedContatosRouteWithChildren
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/senha/esqueci': typeof SenhaEsqueciRoute
  '/senha/redefinir': typeof SenhaRedefinirRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/ia/agentes': typeof AuthenticatedIaAgentesRoute
  '/ia/habilidades': typeof AuthenticatedIaHabilidadesRoute
  '/ia/propostas': typeof AuthenticatedIaPropostasRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/ia/': typeof AuthenticatedIaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/canal-oficial': typeof AuthenticatedCanalOficialRoute
  '/contatos': typeof AuthenticatedContatosRouteWithChildren
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/senha/esqueci': typeof SenhaEsqueciRoute
  '/senha/redefinir': typeof SenhaRedefinirRoute
  '/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/ia/agentes': typeof AuthenticatedIaAgentesRoute
  '/ia/habilidades': typeof AuthenticatedIaHabilidadesRoute
  '/ia/propostas': typeof AuthenticatedIaPropostasRoute
  '/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/ia': typeof AuthenticatedIaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/canal-oficial': typeof AuthenticatedCanalOficialRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/contatos': typeof AuthenticatedContatosRouteWithChildren
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/respostas-rapidas': typeof AuthenticatedRespostasRapidasRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/senha/esqueci': typeof SenhaEsqueciRoute
  '/senha/redefinir': typeof SenhaRedefinirRoute
  '/_authenticated/contatos/$id': typeof AuthenticatedContatosIdRoute
  '/_authenticated/ia/agentes': typeof AuthenticatedIaAgentesRoute
  '/_authenticated/ia/habilidades': typeof AuthenticatedIaHabilidadesRoute
  '/_authenticated/ia/propostas': typeof AuthenticatedIaPropostasRoute
  '/_authenticated/negocios/$id': typeof AuthenticatedNegociosIdRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/ia/': typeof AuthenticatedIaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/canal-oficial'
    | '/configuracoes'
    | '/contatos'
    | '/equipe'
    | '/fila'
    | '/funil'
    | '/metricas'
    | '/modelos'
    | '/painel'
    | '/respostas-rapidas'
    | '/tarefas'
    | '/whatsapp'
    | '/senha/esqueci'
    | '/senha/redefinir'
    | '/contatos/$id'
    | '/ia/agentes'
    | '/ia/habilidades'
    | '/ia/propostas'
    | '/negocios/$id'
    | '/configuracoes/'
    | '/ia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/canal-oficial'
    | '/contatos'
    | '/equipe'
    | '/fila'
    | '/funil'
    | '/metricas'
    | '/modelos'
    | '/painel'
    | '/respostas-rapidas'
    | '/tarefas'
    | '/whatsapp'
    | '/senha/esqueci'
    | '/senha/redefinir'
    | '/contatos/$id'
    | '/ia/agentes'
    | '/ia/habilidades'
    | '/ia/propostas'
    | '/negocios/$id'
    | '/configuracoes'
    | '/ia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/canal-oficial'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/equipe'
    | '/_authenticated/fila'
    | '/_authenticated/funil'
    | '/_authenticated/metricas'
    | '/_authenticated/modelos'
    | '/_authenticated/painel'
    | '/_authenticated/respostas-rapidas'
    | '/_authenticated/tarefas'
    | '/_authenticated/whatsapp'
    | '/senha/esqueci'
    | '/senha/redefinir'
    | '/_authenticated/contatos/$id'
    | '/_authenticated/ia/agentes'
    | '/_authenticated/ia/habilidades'
    | '/_authenticated/ia/propostas'
    | '/_authenticated/negocios/$id'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/ia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SenhaEsqueciRoute: typeof SenhaEsqueciRoute
  SenhaRedefinirRoute: typeof SenhaRedefinirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canal-oficial': {
      id: '/_authenticated/canal-oficial'
      path: '/canal-oficial'
      fullPath: '/canal-oficial'
      preLoaderRoute: typeof AuthenticatedCanalOficialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/respostas-rapidas': {
      id: '/_authenticated/respostas-rapidas'
      path: '/respostas-rapidas'
      fullPath: '/respostas-rapidas'
      preLoaderRoute: typeof AuthenticatedRespostasRapidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/senha/esqueci': {
      id: '/senha/esqueci'
      path: '/senha/esqueci'
      fullPath: '/senha/esqueci'
      preLoaderRoute: typeof SenhaEsqueciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senha/redefinir': {
      id: '/senha/redefinir'
      path: '/senha/redefinir'
      fullPath: '/senha/redefinir'
      preLoaderRoute: typeof SenhaRedefinirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/contatos/$id': {
      id: '/_authenticated/contatos/$id'
      path: '/$id'
      fullPath: '/contatos/$id'
      preLoaderRoute: typeof AuthenticatedContatosIdRouteImport
      parentRoute: typeof AuthenticatedContatosRoute
    }
    '/_authenticated/ia/': {
      id: '/_authenticated/ia/'
      path: '/ia'
      fullPath: '/ia/'
      preLoaderRoute: typeof AuthenticatedIaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia/agentes': {
      id: '/_authenticated/ia/agentes'
      path: '/ia/agentes'
      fullPath: '/ia/agentes'
      preLoaderRoute: typeof AuthenticatedIaAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia/habilidades': {
      id: '/_authenticated/ia/habilidades'
      path: '/ia/habilidades'
      fullPath: '/ia/habilidades'
      preLoaderRoute: typeof AuthenticatedIaHabilidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia/propostas': {
      id: '/_authenticated/ia/propostas'
      path: '/ia/propostas'
      fullPath: '/ia/propostas'
      preLoaderRoute: typeof AuthenticatedIaPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios/$id': {
      id: '/_authenticated/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof AuthenticatedNegociosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedContatosRouteChildren {
  AuthenticatedContatosIdRoute: typeof AuthenticatedContatosIdRoute
}

const AuthenticatedContatosRouteChildren: AuthenticatedContatosRouteChildren = {
  AuthenticatedContatosIdRoute: AuthenticatedContatosIdRoute,
}

const AuthenticatedContatosRouteWithChildren =
  AuthenticatedContatosRoute._addFileChildren(
    AuthenticatedContatosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCanalOficialRoute: typeof AuthenticatedCanalOficialRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRouteWithChildren
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRespostasRapidasRoute: typeof AuthenticatedRespostasRapidasRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedIaAgentesRoute: typeof AuthenticatedIaAgentesRoute
  AuthenticatedIaHabilidadesRoute: typeof AuthenticatedIaHabilidadesRoute
  AuthenticatedIaPropostasRoute: typeof AuthenticatedIaPropostasRoute
  AuthenticatedNegociosIdRoute: typeof AuthenticatedNegociosIdRoute
  AuthenticatedIaIndexRoute: typeof AuthenticatedIaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCanalOficialRoute: AuthenticatedCanalOficialRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedContatosRoute: AuthenticatedContatosRouteWithChildren,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRespostasRapidasRoute: AuthenticatedRespostasRapidasRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedIaAgentesRoute: AuthenticatedIaAgentesRoute,
  AuthenticatedIaHabilidadesRoute: AuthenticatedIaHabilidadesRoute,
  AuthenticatedIaPropostasRoute: AuthenticatedIaPropostasRoute,
  AuthenticatedNegociosIdRoute: AuthenticatedNegociosIdRoute,
  AuthenticatedIaIndexRoute: AuthenticatedIaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SenhaEsqueciRoute: SenhaEsqueciRoute,
  SenhaRedefinirRoute: SenhaRedefinirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
